blueprint:
  name: Sonoff Ultimate TX automation Blueprint
  description: >-
    Sonoff Ultimate TX blueprint for "two fingers double click" gesture and "two fingers + slide action".
    Uses Sonoff LAN HACS integration - https://github.com/AlexxIT/SonoffLAN.
    Requires a manually created text helper for last event state.
  domain: automation
  homeassistant:
    min_version: "2024.10.0"
  author: Shadala (fork)
  source_url: https://github.com/tavarez992/HomeassistantBlueprints/blob/main/blueprints/automation/SonoffUltimateTX.yaml
  input:
    entities_section:
      name: Entities
      icon: mdi:cellphone-link
      input:
        controller_ambient:
          name: (Required) Ambient light entity
          description: Ambient
          selector:
            entity:
              domain:
                - light
        controller_entity:
          name: (Required) Entity with slide actions
          description: Slide
          selector:
            entity:
              domain:
                - sensor
        helper_last_controller_event:
          name: (Required) Helper - Last Event
          description: Input Text used to store the last event. You will need to manually create a text input entity for this.
          selector:
            entity:
              domain:
                - input_text
    actions_section:
      name: Actions
      icon: mdi:gesture-tap-button
      input:
        action_single_actions_slide_1:
          name: Single slide left
          description: Slide left
          default: []
          selector:
            action: {}
        action_single_actions_slide_2:
          name: Single slide right
          description: Slide right
          default: []
          selector:
            action: {}
        action_double_actions_double_ambient_click:
          name: Double click with two fingers
          description: Two times click with two fingers gesture
          default: []
          selector:
            action: {}
        action_double_actions_slide_1:
          name: Slide left after two fingers
          description: Two fingers gesture then slide left
          default: []
          selector:
            action: {}
        action_double_actions_slide_2:
          name: Slide right after two fingers
          description: Two fingers gesture then slide right
          default: []
          selector:
            action: {}
    helpers_section:
      name: Helpers
      icon: mdi:application-variable
      collapsed: true
      input:
        helper_double_press_delay:
          name: (Optional) Helper - Double Press delay
          description: Max delay between the first and the second DOUBLE events.
          default: 1000
          selector:
            number:
              min: 100.0
              max: 5000.0
              unit_of_measurement: milliseconds
              mode: box
              step: 10.0

mode: restart
max_exceeded: silent

triggers:
  - id: ambient_change
    trigger: state
    entity_id: !input controller_ambient
  - id: slide_left
    trigger: state
    entity_id: !input controller_entity
    to: slide_1
  - id: slide_right
    trigger: state
    entity_id: !input controller_entity
    to: slide_2

conditions:
  - condition: template
    value_template: >-
      {{ trigger.to_state.state in ['on','off','slide_1','slide_2'] and
      trigger.to_state.context.parent_id is none }}

action:
  - variables:
      helper_last_controller_event: !input helper_last_controller_event
      helper_double_press_delay: !input helper_double_press_delay
      trigger_action: "{{ trigger.to_state.state }}"
      trigger_delta: >-
        {{ (as_timestamp(now()) - ((states(helper_last_controller_event) | from_json).t
        if states(helper_last_controller_event) is string and states(helper_last_controller_event) | regex_match("^\{((\"a\":\".*\"|\"t\":\d+\.\d+)(,)?){2}\}$")
        else as_timestamp("1970-01-01 00:00:00"))) * 1000 }}
      last_controller_event: >-
        {{ (states(helper_last_controller_event) | from_json).a
        if states(helper_last_controller_event) is string and states(helper_last_controller_event) | regex_match("^\{((\"a\":\".*\"|\"t\":\d+\.\d+)(,)?){2}\}$")
        else "" }}
      time_to_do_double: >-
        {{ trigger_delta | int <= helper_double_press_delay | int and last_controller_event in ['on','off'] }}
  - action: input_text.set_value
    data:
      value: "{{ {'a': trigger_action, 't': as_timestamp(now())} | to_json }}"
    target:
      entity_id: !input helper_last_controller_event
  - if:
      - "{{ time_to_do_double }}"
    then:
      - choose:
          - conditions: "{{ trigger_action == 'slide_1' }}"
            sequence:
              - action: input_text.set_value
                data:
                  value: "{{ {'a':'do_second_left','t':as_timestamp(now())} | to_json }}"
                target:
                  entity_id: !input helper_last_controller_event
              - choose: []
                sequence: !input action_double_actions_slide_1
          - conditions: "{{ trigger_action == 'slide_2' }}"
            sequence:
              - action: input_text.set_value
                data:
                  value: "{{ {'a':'do_second_right','t':as_timestamp(now())} | to_json }}"
                target:
                  entity_id: !input helper_last_controller_event
              - choose: []
                sequence: !input action_double_actions_slide_2
          - conditions: "{{ trigger_action in ['on','off'] }}"
            sequence:
              - action: input_text.set_value
                data:
                  value: "{{ {'a':'double_ambient_click','t':as_timestamp(now())} | to_json }}"
                target:
                  entity_id: !input helper_last_controller_event
              - choose: []
                sequence: !input action_double_actions_double_ambient_click
    else:
      - if:
          - "{{ trigger_action in ['on','off'] }}"
        then:
          - delay:
              milliseconds: "{{ helper_double_press_delay }}"
      - choose:
          - conditions: "{{ trigger_action == 'slide_1' }}"
            sequence:
              - action: input_text.set_value
                data:
                  value: "{{ {'a':'do_single_left','t':as_timestamp(now())} | to_json }}"
                target:
                  entity_id: !input helper_last_controller_event
              - choose: []
                sequence: !input action_single_actions_slide_1
          - conditions: "{{ trigger_action == 'slide_2' }}"
            sequence:
              - action: input_text.set_value
                data:
                  value: "{{ {'a':'do_single_right','t':as_timestamp(now())} | to_json }}"
                target:
                  entity_id: !input helper_last_controller_event
              - choose: []
                sequence: !input action_single_actions_slide_2
